"""Simulation data registry generator.

Scans ``data/`` for binary metadata sidecar files (``.bin.meta.json``),
parses them, and writes a YAML registry (``data/_registry.yml``) that
catalogues every simulation dataset with its resolution, realm, backend,
point counts, and file paths.

Usage::

    python3 -m src.utils.registry          # generate data/_registry.yml
    python3 -m src.utils.registry --check  # verify registry is up to date
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


# Canonical resolution grid.
RESOLUTION_GRID: list[int] = [
    10, 20, 30, 40, 50, 60, 70, 80, 90, 100,
    125, 150, 175, 200,
    300, 400, 500,
]

# Default physics parameters shared across all simulations.
PHYSICS_DEFAULTS: dict[str, object] = {
    "dt": 0.01,
    "t_max": 15.0,
    "theta_range": [-170.0, 170.0],
    "masses": [1, 1, 1],
    "lengths": [1, 1, 1],
    "g": 9.81,
}

DATA_DIR = Path("data")
REGISTRY_PATH = DATA_DIR / "_registry.yml"


def _parse_meta_file(meta_path: Path) -> dict | None:
    """Parse a ``.bin.meta.json`` sidecar into a registry entry dict."""
    try:
        with open(meta_path, encoding="utf-8") as fh:
            raw = json.load(fh)
    except (json.JSONDecodeError, OSError):
        return None

    metadata = raw.get("metadata", {})
    bin_path = meta_path.with_name(meta_path.name.replace(".meta.json", ""))
    json_stem = bin_path.stem  # e.g. simulation_100_gpu
    json_path = bin_path.with_suffix(".json")

    resolution = raw.get("grid_size", 0)
    realm = raw.get("grid_type", "cube")
    backend = metadata.get("backend", "unknown")
    total_points = metadata.get("total_points", metadata.get("num_pendulums", 0))
    total_flipped = metadata.get("total_flipped", metadata.get("num_flipped", 0))
    fraction_flipped = metadata.get("fraction_flipped", 0.0)
    wall_time = metadata.get("wall_time_seconds", 0.0)
    date = metadata.get("date", "")

    files: dict[str, str] = {}
    if bin_path.exists():
        files["bin"] = bin_path.name
    if meta_path.exists():
        files["meta"] = meta_path.name
    if json_path.exists():
        files["json"] = json_path.name

    return {
        "resolution": resolution,
        "realm": realm,
        "backend": backend,
        "total_points": total_points,
        "total_flipped": total_flipped,
        "fraction_flipped": round(fraction_flipped, 6),
        "wall_time_seconds": round(wall_time, 2),
        "date": date,
        "files": files,
    }


def scan_datasets(data_directory: Path | None = None) -> list[dict]:
    """Scan a data directory for simulation datasets.

    Returns a sorted list of dataset entry dicts (by realm, then resolution).
    """
    directory = data_directory or DATA_DIR
    meta_files = sorted(directory.glob("simulation_*.bin.meta.json"))

    datasets = []
    for meta_path in meta_files:
        entry = _parse_meta_file(meta_path)
        if entry is not None:
            datasets.append(entry)

    datasets.sort(key=lambda d: (d["realm"], d["backend"], d["resolution"]))
    return datasets


def _yaml_list(items: list, indent: int = 2) -> str:
    """Format a simple list as inline YAML."""
    return "[" + ", ".join(str(item) for item in items) + "]"


def generate_registry_yaml(datasets: list[dict]) -> str:
    """Generate YAML registry content from a list of dataset entries."""
    lines = [
        "# Triple Pendulum Simulation Data Registry",
        "# Auto-generated by src.utils.registry -- do not edit manually",
        f"schema_version: 1",
        f"generated: \"{datetime.now(timezone.utc).isoformat()}\"",
        f"total_datasets: {len(datasets)}",
        "",
        "resolution_grid:",
        f"  fine: {_yaml_list(RESOLUTION_GRID[:10])}",
        f"  medium: {_yaml_list(RESOLUTION_GRID[10:14])}",
        f"  coarse: {_yaml_list(RESOLUTION_GRID[14:])}",
        "",
        "physics:",
    ]

    for key, value in PHYSICS_DEFAULTS.items():
        if isinstance(value, list):
            lines.append(f"  {key}: {_yaml_list(value)}")
        else:
            lines.append(f"  {key}: {value}")

    lines.append("")
    lines.append("datasets:")

    for entry in datasets:
        lines.append(f"  - resolution: {entry['resolution']}")
        lines.append(f"    realm: {entry['realm']}")
        lines.append(f"    backend: {entry['backend']}")
        lines.append(f"    total_points: {entry['total_points']}")
        lines.append(f"    total_flipped: {entry['total_flipped']}")
        lines.append(f"    fraction_flipped: {entry['fraction_flipped']}")
        lines.append(f"    wall_time_seconds: {entry['wall_time_seconds']}")
        lines.append(f"    date: \"{entry['date']}\"")
        lines.append(f"    files:")
        for file_key, file_name in sorted(entry["files"].items()):
            lines.append(f"      {file_key}: {file_name}")

    lines.append("")
    return "\n".join(lines)


def write_registry(data_directory: Path | None = None) -> Path:
    """Scan datasets and write the registry YAML file.

    Returns the path to the written registry file.
    """
    directory = data_directory or DATA_DIR
    registry_path = directory / "_registry.yml"

    datasets = scan_datasets(directory)
    yaml_content = generate_registry_yaml(datasets)

    registry_path.write_text(yaml_content, encoding="utf-8")
    return registry_path


def check_registry(data_directory: Path | None = None) -> bool:
    """Check if the registry is up to date with the data directory.

    Returns True if the registry matches, False otherwise.
    """
    directory = data_directory or DATA_DIR
    registry_path = directory / "_registry.yml"

    if not registry_path.exists():
        print(f"Registry not found: {registry_path}")
        return False

    current_content = registry_path.read_text(encoding="utf-8")
    datasets = scan_datasets(directory)
    expected_content = generate_registry_yaml(datasets)

    # Compare line by line, ignoring the generated timestamp.
    current_lines = [
        line for line in current_content.splitlines()
        if not line.startswith("generated:")
    ]
    expected_lines = [
        line for line in expected_content.splitlines()
        if not line.startswith("generated:")
    ]

    if current_lines == expected_lines:
        print(f"Registry is up to date ({len(datasets)} datasets)")
        return True

    print(f"Registry is STALE — expected {len(datasets)} datasets")
    return False


def main(cli_args: list[str] | None = None) -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="python3 -m src.utils.registry",
        description="Generate or check the simulation data registry.",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Check if registry is up to date (exit 1 if stale)",
    )
    parser.add_argument(
        "--data-dir", type=str, default=None,
        help="Data directory to scan (default: data/)",
    )
    args = parser.parse_args(cli_args)

    data_directory = Path(args.data_dir) if args.data_dir else None

    if args.check:
        is_current = check_registry(data_directory)
        sys.exit(0 if is_current else 1)

    registry_path = write_registry(data_directory)
    datasets = scan_datasets(data_directory)
    print(f"Registry written: {registry_path} ({len(datasets)} datasets)")


if __name__ == "__main__":
    main()
